### PR TITLE
Update RealWorld Application

### PR DESCRIPTION
**Pull request by lharzenetter**
@JanFuhrmann

Real World with MySQL DB

### CODE REVIEW

**Comment by lharzenetter** [comment]
Current problem is, that somehow java is not always completely installed. Does the container somehow exit the script early?

**Comment by nyuuyn** [comment]
Maybe the java 11 installation needs the upate-alternatives stuff as in java 8 ?

https://github.com/OpenTOSCA/tosca-definitions-common/blob/main/artifacttemplates/http%253A%252F%252Fopentosca.org%252Fartifacttemplates/Java_11-Install-w1/files/install.sh

https://github.com/OpenTOSCA/tosca-definitions-common/blob/main/artifacttemplates/http%253A%252F%252Fopentosca.org%252Fartifacttemplates/Java_8-Install-w1/files/install.sh

**Comment by lharzenetter** [comment]
@nyuuyn, do you want to try it?

**Review by nyuuyn — APPROVED** [review]
LGAWT/FM

**Pull request merged**
